title = "MoshangUSA"
baseURL = "https://moshangusa.github.io"
languageCode = "en-us"
theme = "ananke" 

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
    [languages.zh]
        title = "陌上美国"
        weight = 1
        contentDir = "content/zh/"
    [languages.en]
        title = "Moshang USA"
        weight = 2
        contentDir = "content/en/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  date_format = "2. January 2006"
  recent_posts_number = 3
  description = "U.S News, Info, and Opinions"
  author = "MoshangUSA team"
  favicon = "favicon.ico"
  site_logo = ""
  custom_css = ['custom.css']

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/MoshangUsa"

[[params.ananke_socials]]
 name = "telegram"
 url = "https://t.me/MoshangUS"